AWSTemplateFormatVersion: '2010-09-09'
Description: 'GrupoLink - RDS PostgreSQL 16'

Parameters:
  Environment:
    Type: String
    Default: prod
  VPCStackName:
    Type: String
    Default: grupolink-vpc
  DBPassword:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t3.micro, db.t3.small, db.t3.medium, db.r6g.large]

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: GrupoLink RDS Subnet Group
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet1' }
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet2' }

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub grupolink-${Environment}
      Engine: postgres
      EngineVersion: '16.3'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: '20'
      MaxAllocatedStorage: 100
      StorageType: gp3
      StorageEncrypted: true
      DBName: whatsapp_saas
      MasterUsername: postgres
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-DataSg' }
      MultiAZ: !If [IsProd, true, false]
      BackupRetentionPeriod: 7
      PreferredBackupWindow: 03:00-04:00
      PreferredMaintenanceWindow: sun:04:00-sun:05:00
      EnablePerformanceInsights: true
      DeletionProtection: !If [IsProd, true, false]
      Tags:
        - Key: Project
          Value: grupolink
        - Key: Environment
          Value: !Ref Environment

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-RDSEndpoint"
  RDSPort:
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-RDSPort"
