AWSTemplateFormatVersion: '2010-09-09'
Description: 'GrupoLink - ElastiCache Redis 7'

Parameters:
  Environment:
    Type: String
    Default: prod
  VPCStackName:
    Type: String
    Default: grupolink-vpc
  NodeType:
    Type: String
    Default: cache.t3.micro
    AllowedValues: [cache.t3.micro, cache.t3.small, cache.r6g.large]

Resources:
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: GrupoLink ElastiCache Subnet Group
      SubnetIds:
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet1' }
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet2' }

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: GrupoLink Redis
      ReplicationGroupId: !Sub grupolink-${Environment}
      CacheNodeType: !Ref NodeType
      Engine: redis
      EngineVersion: '7.1'
      NumCacheClusters: !If [IsProd, 2, 1]
      AutomaticFailoverEnabled: !If [IsProd, true, false]
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      SecurityGroupIds:
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-DataSg' }
      SnapshotRetentionLimit: !If [IsProd, 5, 1]

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  RedisEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-RedisEndpoint"
  RedisPort:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub "${AWS::StackName}-RedisPort"
