AWSTemplateFormatVersion: '2010-09-09'
Description: 'GrupoLink - Amazon MQ (RabbitMQ)'

Parameters:
  Environment:
    Type: String
    Default: prod
  VPCStackName:
    Type: String
    Default: grupolink-vpc
  RabbitMQUser:
    Type: String
    Default: grupolink
  RabbitMQPassword:
    Type: String
    NoEcho: true
  BrokerInstanceType:
    Type: String
    Default: mq.t3.micro
    AllowedValues: [mq.t3.micro, mq.m5.large]

Resources:
  RabbitMQBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      BrokerName: !Sub grupolink-${Environment}
      EngineType: RABBITMQ
      EngineVersion: '3.13'
      HostInstanceType: !Ref BrokerInstanceType
      DeploymentMode: !If [IsProd, CLUSTER_MULTI_AZ, SINGLE_INSTANCE]
      PubliclyAccessible: false
      SubnetIds:
        - !If
          - IsProd
          - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet1' }
          - !ImportValue { 'Fn::Sub': '${VPCStackName}-PrivateSubnet1' }
      SecurityGroups:
        - !ImportValue { 'Fn::Sub': '${VPCStackName}-DataSg' }
      Users:
        - Username: !Ref RabbitMQUser
          Password: !Ref RabbitMQPassword
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Project
          Value: grupolink
        - Key: Environment
          Value: !Ref Environment

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

Outputs:
  RabbitMQEndpoint:
    Value: !Select [0, !GetAtt RabbitMQBroker.AmqpEndpoints]
    Export:
      Name: !Sub "${AWS::StackName}-RabbitMQEndpoint"
